version: '3'
services:
  # Application Dockerfile is in same folder which is .
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  # db is in the db folder
  app:
    build: .